// WNC CMS Config — Auto-generated by WNC Content Manager
// Last updated: 2025-03-06
// DO NOT EDIT MANUALLY — use the WNC portal to make changes
window.__WNC_CONFIG = {
  promoBanner: {
    enabled: true,
    text: "\ud83c\udf89 Upcoming Event \u2014 Moms Night Out! Tickets just $65",
    linkText: "Get Tickets \u2192",
    linkUrl: "#tickets",
    bgColor: "#1a3a4a",
    textColor: "#ffffff",
    accentColor: "#f5a623"
  },
  floatingCta: {
    enabled: true,
    text: "\ud83c\udf9f\ufe0f Buy Tickets",
    url: "#tickets",
    bgColor: "#f5a623",
    textColor: "#1a3a4a"
  }
};
